JoypadUp			equ	$01		; Joystick direction defines
JoypadRight			equ	$02	
JoypadDown			equ	$04	
JoypadLeft			equ	$08	
Button1				equ	$10	
Button2				equ	$20	
JoypadUpBit			equ	$00		; Joystick direction bit defines
JoypadRightBit		equ	$01	
JoypadDownBit		equ	$02	
JoypadLeftBit		equ	$03	
Button1Bit			equ	$04	
Button2Bit			equ	$05	
Joysticks			equ	2		; Joysticks supported
JoystickButtons		equ	2		; Joystick buttons supported
